### ISSUE TITLE
Job List not loading with latest updated Chrome version.

### ISSUE THREAD

**Issue by Vikram-BM** [wimpywarlord/appliFLY#11]
Error: (as seen on CMD)
DevTools listening on ws://127.0.0.1:8871/devtools/browser/f6ae2085-ff59-43ef-aee1-3443364b7b74
An error occured. Please document & report it to the developer @https://github.com/wimpywarlord
'NoneType' object is not iterable

Tried several times, it goes to on campus jobs -> ASU login page and then crashes and closes the browser window.

Any solutions here ?

**Comment by Vikram-BM** [comment]
Fixed this issue. Facing this another issue:

DevTools listening on ws://127.0.0.1:10805/devtools/browser/11bad18e-fb8e-4d00-91b8-cd017619aaf4
All jobs staged for application.
An error occured. Please document & report it to the developer @https://github.com/wimpywarlord/appliFLY/issues
Message: 
Stacktrace:
        GetHandleVerifier [0x00007FF69F6052A2+57122]
        (No symbol) [0x00007FF69F57EA92]
        (No symbol) [0x00007FF69F44E3AB]
        (No symbol) [0x00007FF69F487D3E]
        (No symbol) [0x00007FF69F487E2C]
        (No symbol) [0x00007FF69F4C0B67]
        (No symbol) [0x00007FF69F4A701F]
        (No symbol) [0x00007FF69F4BEB82]
        (No symbol) [0x00007FF69F4A6DB3]
        (No symbol) [0x00007FF69F47D2B1]
        (No symbol) [0x00007FF69F47E494]
        GetHandleVerifier [0x00007FF69F8AEF82+2849794]
        GetHandleVerifier [0x00007FF69F901D24+3189156]
        GetHandleVerifier [0x00007FF69F8FACAF+3160367]
        GetHandleVerifier [0x00007FF69F696D06+653702]
        (No symbol) [0x00007FF69F58A208]
        (No symbol) [0x00007FF69F5862C4]
        (No symbol) [0x00007FF69F5863F6]
        (No symbol) [0x00007FF69F5767A3]
        BaseThreadInitThunk [0x00007FFFDA847344+20]
        RtlUserThreadStart [0x00007FFFDAE026B1+33]

**Comment by Vikram-BM** [comment]
Chrome is up to date
Version 117.0.5938.89 (Official Build) (64-bit)

**Comment by Vikram-BM** [comment]
@wimpywarlord 
![image](https://github.com/wimpywarlord/appliFLY/assets/60289890/687b075a-ddd9-41ef-9f73-df4396eaba6f)

**Comment by Vikram-BM** [comment]
@wimpywarlord Any idea here please ?

**Comment by wimpywarlord** [comment]
Hey thankyou for such a detailed bug report. I will start looking into this. 

A screen recording of the bug would really help as well (Do remember to hide your credentials)

Lastly,

For a quick remedy try to run the script on your friend's laptop, because the script is proven to run on many machines. Also try experimenting with the network speed.

**Comment by wimpywarlord** [comment]
I am trying to introduce a firefox driver to mitigate this issue: https://stackoverflow.com/questions/48055427/selenium-webdriver-will-not-fully-load-page-python

**Comment by Vikram-BM** [comment]
Okay Understood. I have shared the video recording of the bug on your whatsapp shared on LinkedIn for privacy. 
Let me know if you need any other information. I will try to do it with other laptop/ devices.

**Comment by wimpywarlord** [comment]
### Solution

This turned out to versioning issue, between selenium driver, python and chrome.

I found an error in the script logs saying:

`ERROR:page_load_metrics_update_dispatcher.cc(194)] Invalid first_paint error using Selenium Python ChromeDriver`

Upon surfing the web, I found this thread: https://stackoverflow.com/questions/75830184/errorpage-load-metrics-update-dispatcher-cc194-invalid-first-paint-error-usi

It talks about how the above error message indicates that there is a mismatch between the binary versions you are using.

On a more deeper level

As per the [[comment](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341#c1)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341#c1) within the [[discussion](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341):

> The supported configuration is to always match the version between Chrome and ChromeDriver - so when you are using Chrome 80, you should use Chrome 80. It is also possible to run ChromeDriver N with Chrome N+1, but this will always generate the warning you see. Most operations will complete successfully, but it is not the recommended approach.
> 
> 
> The solution is to upgrade ChromeDriver to version 80: https://chromedriver.chromium.org/downloads
> 

This is understandable because, most of the operations were working fine in the script, but some operations were acting wonky.

***The straight and simple solution is to***

You need to ensure:

- **ChromeDriver** is updated to the latest version - as of 21st October 2023 - that is 118.0.XXXX.X family

Go to Google’s official driver support website: https://chromedriver.chromium.org/downloads and then go to the downloads section : https://googlechromelabs.github.io/chrome-for-testing/

Download the latest stable version of the chrome driver according to your operating system : https://googlechromelabs.github.io/chrome-for-testing/#stable

Copy the absolute path to the `chrome.exe` file inside the downloaded chrome driver folder.
    
    
    Look into line number 61 in [appliFly.py](http://appliFly.py) file and uncomment as well as update the absolute path to the chrome driver which you just downloaded from the above mentioned link.
    
    ```
    # You can use other drivers like Firefox, Edge, etc.
    
      # ____________ If Facing Jobs 0 Jobs found issue ________________
      # Absolute Path to Chrome Driver Example: C:\Users\ASUS\Downloads\chrome\chrome.exe
      # chromeDriver = webdriver.Chrome(executable_path=r"Absolute Path to the Chrome Driver")  # Uncomment this if facing 0 jobs found issue
      # ____________ No Erros ____________________
      chromeDriver = webdriver.Chrome()  # Comment this out if facing 0 jobs found issue
    ```
    

- **Chrome Browser** is updated to the latest version - as of 21st October 2023 - that is the 118.0.XXX.X family 

Download the latest version chrome or update the existing version to the latest version. Here is how: https://support.google.com/chrome/answer/95414?hl=en&co=GENIE.Platform%3DDesktop

- **Selenium** is upgraded to current released ***[[Version 4.8.0](https://www.selenium.dev/downloads/)](https://www.selenium.dev/downloads/)***.
I have updated the requirements.txt file to include selenium `selenium==4.14.0` instead of `selenium==4.12.0`

Therefore re-clone the repository from Github and do a fresh `pip install -r requirements.txt`

**Comment by wimpywarlord** [comment]
Hey, @Vikram-BM  I would be more than happy to assist you with this over a call if you are unable to figure it out.

Shoot any questions that you may have.

**Comment by Vikram-BM** [comment]
Understood. Will try this and let you know.

**Comment by Vikram-BM** [comment]
Its working !! Thanks a lot for resolving the bug.
