### ISSUE TITLE
an error occured

### ISSUE THREAD

**Issue by adityaraoyt** [wimpywarlord/appliFLY#12]
Message:
Stacktrace:
        GetHandleVerifier [0x00007FF74C5F7D12+55474]
        (No symbol) [0x00007FF74C5677C2]
        (No symbol) [0x00007FF74C41E0EB]
        (No symbol) [0x00007FF74C45EBAC]
        (No symbol) [0x00007FF74C45ED2C]
        (No symbol) [0x00007FF74C499F77]
        (No symbol) [0x00007FF74C47F19F]
        (No symbol) [0x00007FF74C497EF2]
        (No symbol) [0x00007FF74C47EF33]
        (No symbol) [0x00007FF74C453D41]
        (No symbol) [0x00007FF74C454F84]
        GetHandleVerifier [0x00007FF74C95B762+3609346]
        GetHandleVerifier [0x00007FF74C9B1A80+3962400]
        GetHandleVerifier [0x00007FF74C9A9F0F+3930799]
        GetHandleVerifier [0x00007FF74C693CA6+694342]
        (No symbol) [0x00007FF74C572218]
        (No symbol) [0x00007FF74C56E484]
        (No symbol) [0x00007FF74C56E5B2]
        (No symbol) [0x00007FF74C55EE13]
        BaseThreadInitThunk [0x00007FFA5A2F257D+29]
        RtlUserThreadStart [0x00007FFA5AFAAA68+40]

**Comment by adityaraoyt** [comment]
it didn't apply to a single job

**Comment by wimpywarlord** [comment]
### Solution

This turned out to versioning issue, between selenium driver, python and chrome.

I found an error in the script logs saying:

`ERROR:page_load_metrics_update_dispatcher.cc(194)] Invalid first_paint error using Selenium Python ChromeDriver`

Upon surfing the web, I found this thread: https://stackoverflow.com/questions/75830184/errorpage-load-metrics-update-dispatcher-cc194-invalid-first-paint-error-usi

It talks about how the above error message indicates that there is a mismatch between the binary versions you are using.

On a more deeper level

As per the [[comment](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341#c1)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341#c1) within the [[discussion](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341):

> The supported configuration is to always match the version between Chrome and ChromeDriver - so when you are using Chrome 80, you should use Chrome 80. It is also possible to run ChromeDriver N with Chrome N+1, but this will always generate the warning you see. Most operations will complete successfully, but it is not the recommended approach.
> 
> 
> The solution is to upgrade ChromeDriver to version 80: https://chromedriver.chromium.org/downloads
> 

This is understandable because, most of the operations were working fine in the script, but some operations were acting wonky.

***The straight and simple solution is to***

You need to ensure:

- **ChromeDriver** is updated to the latest version - as of 21st October 2023 - that is 118.0.XXXX.X family

Go to Google’s official driver support website: https://chromedriver.chromium.org/downloads and then go to the downloads section : https://googlechromelabs.github.io/chrome-for-testing/

Download the latest stable version of the chrome driver according to your operating system : https://googlechromelabs.github.io/chrome-for-testing/#stable

Copy the absolute path to the `chrome.exe` file inside the downloaded chrome driver folder.
    
    
    Look into line number 61 in [appliFly.py](http://appliFly.py) file and uncomment as well as update the absolute path to the chrome driver which you just downloaded from the above mentioned link.
    
    ```
    # You can use other drivers like Firefox, Edge, etc.
    
      # ____________ If Facing Jobs 0 Jobs found issue ________________
      # Absolute Path to Chrome Driver Example: C:\Users\ASUS\Downloads\chrome\chrome.exe
      # chromeDriver = webdriver.Chrome(executable_path=r"Absolute Path to the Chrome Driver")  # Uncomment this if facing 0 jobs found issue
      # ____________ No Erros ____________________
      chromeDriver = webdriver.Chrome()  # Comment this out if facing 0 jobs found issue
    ```
    

- **Chrome Browser** is updated to the latest version - as of 21st October 2023 - that is the 118.0.XXX.X family 

Download the latest version chrome or update the existing version to the latest version. Here is how: https://support.google.com/chrome/answer/95414?hl=en&co=GENIE.Platform%3DDesktop

- **Selenium** is upgraded to current released ***[[Version 4.8.0](https://www.selenium.dev/downloads/)](https://www.selenium.dev/downloads/)***.
I have updated the requirements.txt file to include selenium `selenium==4.14.0` instead of `selenium==4.12.0`

Therefore re-clone the repository from Github and do a fresh `pip install -r requirements.txt`

**Comment by wimpywarlord** [comment]
Hey, @adityaraoyt I would be more than happy to assist you with this over a call if you are unable to figure it out.

Shoot any questions that you may have.

**Comment by adityaraoyt** [comment]
Hey Kshitij,
Appreciate that bro, I’ll try this again today and if there are still some
problems I’ll let you know.

Thank you

**Comment by wimpywarlord** [comment]
Closing, as resolved
